apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

metadata:
  labels:
    app: hello-deploy

resources:
  - ../../base

patches:
  - path: hello-deploy-deployment.yaml
  - path: hello-deploy-service.yaml


