apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
commonLabels:
  app: argocd-test-app-dev
nameSuffix: -dev

patches:
- ./deployment.yaml
- ./service.yaml

images:
- name: argocd-test-app

resources:
- ../../base
