apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

metadata:
  labels:
    app: argocd-test-app-dev

patches:
  - path: ../../base/deployment.yaml
  - path: ../../base/service.yaml

resources:
  - ../../base
