apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

commonLabels:
  app: argocd-test-app-dev
nameSuffix: -dev

patches:
  - path: ../../../base/deployment.yaml
  - path: ../../../base/service.yaml

resources:
- ../../../base
