apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-test-app-deployment
spec:
  strategy: # 올바른 필드
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: argocd-test-app
  template:
    metadata:
      labels:
        app: argocd-test-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80