apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-test-deployment
  labels:
    app: argocd-test
spec:
  strategy: # 올바른 필드
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: test-argocd
  template:
    metadata:
      labels:
        app: test-argocd
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80