apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy-deployment
  labels:
    app: hello-deploy
spec:
  strategy: # 올바른 필드
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: hello-deploy
  template:
    metadata:
      labels:
        app: hello-deploy
    spec:
      containers:
        - name: hello-deploy
          image: cqqcsa/test:v1
          ports:
            - containerPort: 8080