apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
metadata:
  labels:
    app: argocd-test-app

images:
  - name: argocd-test-app
    
resources:
- ./deployment.yaml
- ./service.yaml